//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.PRODUCTO_FALTANTE_ROTO = new HashSet<PRODUCTO_FALTANTE_ROTO>();
        }
    
        public string DetalleProducto { get; set; }
        public decimal PrecioNeto { get; set; }
        public decimal PrecioIva { get; set; }
        public int Cantidad { get; set; }
        public int IDproducto { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public string Rubro { get; set; }
    
        public virtual ICollection<PRODUCTO_FALTANTE_ROTO> PRODUCTO_FALTANTE_ROTO { get; set; }
    }
}
