//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_FALTANTE_ROTO
    {
        public int Id_prodFaltaRo { get; set; }
        public int IDproducto { get; set; }
        public int IDproveedor { get; set; }
        public string Detalle { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
