//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.PEDIDO_PROVEEDOR = new HashSet<PEDIDO_PROVEEDOR>();
            this.PRODUCTO_FALTANTE_ROTO = new HashSet<PRODUCTO_FALTANTE_ROTO>();
        }
    
        public string CUIT { get; set; }
        public string RazonSocial { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string ProvinciaCiudad { get; set; }
        public string CodigoPostal { get; set; }
        public int IDproveedor { get; set; }
        public string NumeroDeCuenta1 { get; set; }
        public string NumeroDeCuenta2 { get; set; }
        public string CBU { get; set; }
    
        public virtual ICollection<PEDIDO_PROVEEDOR> PEDIDO_PROVEEDOR { get; set; }
        public virtual ICollection<PRODUCTO_FALTANTE_ROTO> PRODUCTO_FALTANTE_ROTO { get; set; }
    }
}
